apiVersion: v1
kind: Pod
metadata:
  name: streaminglayer
spec:
  containers:
  - image: 'bitnami/zookeeper:latest'
    name: zookeeper
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: yes
    ports:
      - containerPort: 2181
  - image: 'bitnami/kafka:latest'
    name: kafka-server
    env:
    - name: KAFKA_BROKER_ID
      value: 1
    - name: KAFKA_CFG_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    - name: ALLOW_PLAINTEXT_LISTENER
      value: yes
    - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
      value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - name: KAFKA_CFG_LISTENERS
      value: CLIENT://:9092,EXTERNAL://:9093
    - name: KAFKA_CFG_ADVERTISED_LISTENERS
      value: CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
      value: CLIENT
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: 1
  - image: 'sylveriance/kafka-producer'
    name: kafka-producer
---
apiVersion: v1
kind: StatefulSet
metadata:
  name: spark-master
spec:
  serviceName: "spark-master"
  selector:
    matchLabels:
      app: spark-master
  replicas: 1
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
      - name: spark-component
        image: sylveriance/spark-component
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7077
          name: spark-master
      env:
      - name: SPARK_MODE
        value: master
      - name: SPARK_RPC_AUTHENTICATION_ENABLED
        value: no
      - name: SPARK_RPC_ENCRYPTION_ENABLED
        value: no
      - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
        value: no
      - name: SPARK_SSL_ENABLED
        value: no
