apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: streaming_layer
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/managed-by: bitnami
spec:
  selector:
    app: zookeeper
  containers:
    image: bitnami/zookeeper
    name: zookeeper
  ports:
  - port: 2181
    targetPort: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: streaming_layer
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/managed-by: bitnami
spec:
  selector:
    app: kafka
  containers:
    image: bitnami/kafka
    name: kafka
  ports:
  - port: 9092
    targetPort: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: streaming_layer
  labels:
    app.kubernetes.io/component: spark
    app.kubernetes.io/managed-by: bitnami
spec:
  selector:
    app: spark-master
  containers:
    image: bitnami/spark
    name: spark-master
  ports:
  - port: 7077
    targetPort: 7077

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: streaming_layer
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app: mongodb
containers:
  image: mongodb:latest
  name: mongodb
  ports:
  - port: 27017
    targetPort: 27017
