FROM python:3.10

EXPOSE 8501

WORKDIR /home/user/app/batch_layer

COPY . .

RUN apt-get update &&\
    pip install -r requirements.txt

ENTRYPOINT ["streamlit", "run", "dashboard-batch.py", "--server.port=8501", "--server.address=0.0.0.0"]
