FROM python:3.10

RUN mkdir batch_layer/
WORKDIR /home/user/app/batch_layer

COPY . .

RUN apt-get update &&\
    pip install --upgrade pip &&\
    pip install -r requirements.txt

ENTRYPOINT ["python3", "ingestion.py"]