version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: pg-database
    ports:
    - "5432:5432"
    environment: 
    POSTGRES_DB = energy_consumption
    env_file:
    - env_postgres
    volumes:
    - pgdata:/data/db
  
  adminer:
    image: adminer
    restart: always
    ports:
    - "8080:8080"
    
volumes:
    pgdata

